version: "3.8"

services:

  robotics_openproject_backend:
    container_name: robotics_openproject_backend
    build: ./docker/backend
    volumes:
      - builds:/root
      - sources:/robotics-openproject
    environment:
      DB_ADDRESS: 172.20.0.2
    networks:
      backend:
    depends_on:
      - robotics_openproject_builder
      - robotics_openproject_db

  robotics_openproject_builder:
    container_name: robotics_openproject_builder
    build: ./docker/builder
    volumes:
      - builds:/root
      - sources:/robotics-openproject
    environment:
      DB_ADDRESS: 172.20.0.2
    networks:
      backend:
    depends_on:
      - robotics_openproject_db
  
  robotics_openproject_db:
    container_name: robotics_openproject_db
    image: postgres:12.11
    ports:
      - 5432:5432
    restart: always
    networks:
      backend:
        ipv4_address: 172.20.0.2
    environment:
      POSTGRES_DB: "openproject"
      POSTGRES_USER: "openproject"
      POSTGRES_PASSWORD: ${DB_PASSWORD}

volumes:
  builds:
    name: robotics_openproject_builds
    external: false
  sources:
    name: robotics_openproject_sources
    external: false

networks:
  backend:
    ipam:
      config:
        - subnet: 172.20.0.0/24
