version: "3.8"

services:
  robotics_openproject_server:
    container_name: robotics_openproject_server
    image: ubuntu:22.04
    entrypoint: tail -f /dev/null
    volumes:
      - root:/root:rw
    ports:
      - ${PORT}:4200
      - 3200:3200
    depends_on:
      - robotics_openproject_db
  
  robotics_openproject_db:
    container_name: robotics_openproject_db
    image: postgres:12.11
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_DB: "openproject"
      POSTGRES_USER: "openproject"
      POSTGRES_PASSWORD: ${DB_PASSWORD}
